/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChatServer;

import java.text.*;
import java.util.Date;
import java.io.*;
import javax.swing.*;

/**
 *
 * @author Sleepersword
 */
public class ServerForm extends javax.swing.JFrame {

    private Server serverInstance;
    private PrintWriter logWriter;
    
    public ServerForm() {
        initComponents();
        
        try {
            String logFile = String.format("Log_ChatServer_%s_%s.txt", getDate(), getTime(true));
            logWriter = new PrintWriter(new FileWriter(logFile, false));
        } catch (IOException ex) {
            logString("Error while trying to create Log file: " + ex.getMessage());
        }
        
        serverInstance = new Server(1501, "ChatServer", this);
        
    }
    
    public static String getTime(boolean includeSeconds) {
        DateFormat dateFormat = new SimpleDateFormat("HH-mm" + ((includeSeconds)?"-ss":"") );
        Date date = new Date();
        return dateFormat.format(date);
    }
    
    public static String getDate() {
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-YYYY");
        Date date = new Date();
        return dateFormat.format(date);
    }
    
    public final void logMessage(Message msg) {
        if(!msg.Sender.equals("server") && !msg.Receiver.equals("server")) {
            logString(String.format("%s --> %s [%s: %s]", msg.Sender, msg.Receiver ,msg.Type, msg.Text[0]));
        } else if(msg.Sender.equals("server")) {
            logString(String.format("--> %s [%s: %s]", msg.Receiver ,msg.Type, msg.Text[0]));
        } else {
            logString(String.format("<-- %s [%s: %s]", msg.Sender, msg.Type, msg.Text[0]));
        }
    }
    
    public final void logString(String text) {
        String logText = String.format("[%s]  %s\n", getTime(false), text);
        textAreaLog.append(logText);
        logWriter.print(logText);
    }
    
    public void updateStatus(ServerStatus status) {
        lblServerStatus.setText("Serverstatus: " + status.name());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLog = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaLog = new javax.swing.JTextArea();
        lblServerLog = new javax.swing.JLabel();
        lblServerStatus = new javax.swing.JLabel();
        panelStatus = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        tabbedPane1Status = new javax.swing.JTabbedPane();
        menuMain = new javax.swing.JMenuBar();
        buttonServer = new javax.swing.JMenu();
        subButtonStart = new javax.swing.JMenuItem();
        subButtonStop = new javax.swing.JMenuItem();
        buttonUser = new javax.swing.JMenu();
        subButtonShowAccounts = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChatServer 0.1");
        setPreferredSize(new java.awt.Dimension(950, 600));
        setSize(new java.awt.Dimension(950, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelLog.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textAreaLog.setEditable(false);
        textAreaLog.setColumns(20);
        textAreaLog.setRows(5);
        jScrollPane1.setViewportView(textAreaLog);

        lblServerLog.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblServerLog.setText("ServerLog:");

        lblServerStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblServerStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblServerStatus.setText("jLabel2");

        javax.swing.GroupLayout panelLogLayout = new javax.swing.GroupLayout(panelLog);
        panelLog.setLayout(panelLogLayout);
        panelLogLayout.setHorizontalGroup(
            panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addGroup(panelLogLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblServerLog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblServerStatus)))
                .addContainerGap())
        );
        panelLogLayout.setVerticalGroup(
            panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServerLog, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServerStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblStatus.setText("Status:");

        javax.swing.GroupLayout panelStatusLayout = new javax.swing.GroupLayout(panelStatus);
        panelStatus.setLayout(panelStatusLayout);
        panelStatusLayout.setHorizontalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedPane1Status)
                    .addGroup(panelStatusLayout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addGap(0, 402, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelStatusLayout.setVerticalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane1Status, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        buttonServer.setText("Server");

        subButtonStart.setText("Start");
        subButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subButtonStartActionPerformed(evt);
            }
        });
        buttonServer.add(subButtonStart);

        subButtonStop.setText("Stop");
        subButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subButtonStopActionPerformed(evt);
            }
        });
        buttonServer.add(subButtonStop);

        menuMain.add(buttonServer);

        buttonUser.setText("User");

        subButtonShowAccounts.setText("Show Accounts...");
        subButtonShowAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subButtonShowAccountsActionPerformed(evt);
            }
        });
        buttonUser.add(subButtonShowAccounts);

        menuMain.add(buttonUser);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subButtonStartActionPerformed
        if(serverInstance.Status == ServerStatus.Running) {
            logString("Server is already running.");
            return;
        }
        
        Runnable serverRun = () -> {
            serverInstance.init();
            serverInstance.start();            
        };
        new Thread(serverRun).start();
    }//GEN-LAST:event_subButtonStartActionPerformed

    private void subButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subButtonStopActionPerformed
        if(serverInstance.Status != ServerStatus.Default && serverInstance.Status != ServerStatus.Stopped) {
            serverInstance.stop();
        }
    }//GEN-LAST:event_subButtonStopActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(serverInstance.Status != ServerStatus.Default && serverInstance.Status != ServerStatus.Stopped) {
            serverInstance.stop();
        }
        logWriter.close();
    }//GEN-LAST:event_formWindowClosing

    private void subButtonShowAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subButtonShowAccountsActionPerformed
        String title = "Registered Accounts";
        JTextArea tempArea = new JTextArea(serverInstance.Accounts.toString());    
        tempArea.setEditable(false);
        
        JOptionPane.showMessageDialog(null,tempArea,title, JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_subButtonShowAccountsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu buttonServer;
    private javax.swing.JMenu buttonUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblServerLog;
    private javax.swing.JLabel lblServerStatus;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JPanel panelLog;
    private javax.swing.JPanel panelStatus;
    private javax.swing.JMenuItem subButtonShowAccounts;
    private javax.swing.JMenuItem subButtonStart;
    private javax.swing.JMenuItem subButtonStop;
    private javax.swing.JTabbedPane tabbedPane1Status;
    private javax.swing.JTextArea textAreaLog;
    // End of variables declaration//GEN-END:variables
}
